### ISSUE TITLE
Different colour icon for menu bar?

### ISSUE THREAD

**Issue by rvdh70** [tarutin/hovrly#2]
Great little app. Would it be possible to offer an option to change the colour of the icon? As you can see here:  it is a bit dark
![CleanShot 2022-08-15 at 11 01 30@2x](https://user-images.githubusercontent.com/49558872/184690232-e0693a6e-1cf5-44a2-94f8-c0fa49df7e57.jpg)
.

**Comment by jona-hsueh** [comment]
Totally agreed for this, not friendly for dark mode

**Comment by tarutin** [comment]
@jona-hsueh @rvdh70 
I support light&dark themes in app. But.. I think this issue tested on new macbooks and topnav not change the color if you switch themes.

Thanks! I do something with that problem.

**Comment by tarutin** [comment]
> Great little app. Would it be possible to offer an option to change the colour of the icon? As you can see here: it is a bit dark
> ![CleanShot 2022-08-15 at 11 01 30@2x](https://user-images.githubusercontent.com/49558872/184690232-e0693a6e-1cf5-44a2-94f8-c0fa49df7e57.jpg)
> .

Can you write this information:
- Macbook model and year
- MacOS version

**Comment by rvdh70** [comment]
Hi,

I think it is working correctly..

My apologies


Roland

**Comment by tarutin** [comment]
@rvdh70 Hm. Interesting. Why is that problem resolved itself? Maybe you installed new version of MacOS?
@jona-hsueh Do you still have this problem?

**Comment by jimmysmits** [comment]
I face this problem as well. After some more investigation it turns out, it is not related to Dark Mode (the icon switches perfectly from black to white when Dark mode is activated). It has to to with being in Light Mode, but having white icons and letters in the menu bar. I don't know how this is determined. Because this morning I started out with all black icons and letters in the menu bar, but now it turned white irregardless of Dark Mode/Light Mode setting.

![image](https://user-images.githubusercontent.com/61211859/195128353-d592dc05-46c1-40af-84e1-4cdc18084820.png)

MacBook Pro (14-inch, 2021), macOS 12.6

**Comment by rvdh70** [comment]
That might be the issue I cannot replicate when I toy with the setting in System Preference. Do you wnat me to try this automated scheduled dark mode?

100% convinced that triggered the issue


Roland

**Comment by tarutin** [comment]
Thank you all! I`ll testing Auto Theme

**Comment by kunwarsahni01** [comment]
I think this issue has to do with macos automatically changing the color of the icons depending on the color of the wallpaper in the background. I am having this issue as well. I am on a M1 Macbook Pro 14inch: 
<img width="533" alt="Screen Shot 2022-10-24 at 3 39 06 PM" src="https://user-images.githubusercontent.com/22580992/197539382-2ed74d15-aa07-44a3-b123-32fc589f9a82.png">

<img width="589" alt="Screen Shot 2022-10-24 at 3 39 03 PM" src="https://user-images.githubusercontent.com/22580992/197539376-02f0c904-156a-411f-8545-31c84d24f8fe.png">
Images from two different desktops with different wallpapers but the mac is in auto mode in light mode at the current time.

**Comment by jimmysmits** [comment]
@kunwarsahni01 Correct, moreover this happens when you have the 'Dynamic' option activated this changes the colours of the wallpaper (darker or lighter) irregardless of Dark Mode/Light Mode

![image](https://user-images.githubusercontent.com/61211859/197564666-a6da9abc-576c-41b5-9c42-5d304e476617.png)

**Comment by kunwarsahni01** [comment]
> @kunwarsahni01 Correct, moreover this happens when you have the 'Dynamic' option activated this changes the colours of the wallpaper (darker or lighter) irregardless of Dark Mode/Light Mode
> 
> ![image](https://user-images.githubusercontent.com/61211859/197564666-a6da9abc-576c-41b5-9c42-5d304e476617.png)

@jimmysmits I am actually using custom wallpapers so no dynamic wallpaper in this scenario.

**Comment by tarutin** [comment]
Fixed at [2.4.4](https://github.com/tarutin/hovrly/releases/tag/v2.4.4)
