### ISSUE TITLE
Not showing in the menu bar

### ISSUE THREAD

**Issue by simicvm** [tarutin/hovrly#24]
App does not stay in the menu bar. I open the app and it shows the window like in this screenshot. Then when I click outside of that window, it disappears and nothing is shown in the menu bar either. I might be doing something wrong, but I am not sure what 😄 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/13484398/209546823-60d88742-44aa-4a77-b3ce-35e0bf1ccd50.png">

OS: Ventura 13.1
HW: MacBook Pro 14, 2021
Installation: `dmg` file from your website

**Comment by alextuby** [comment]
Hi. I have/had the same issue on my Macbook Air M2. In my case I think it's because of the camera area. When you choose some of the cities "visible" the icon in the menu bar gets too wide, overlaps with the camera area and becomes invisible altogether. I unchecked everything (cities, date) to that it would be just the black circle and it appeared. Then moved it to the far right of the menu bar.
On your screen I see you have a lot of stuff in the menu bar so probably the same issue.

**Comment by tarutin** [comment]
@simicvm Hi! Yes, @alextuby is absolutely right. You can hold CMD button and move the icon.
